### PR TITLE
Table formatting for full width characters

### PR DESCRIPTION
**Pull request by kieran-ryan**
### 🤔 What's changed?

Count full-width characters as 2 spaces to determine table column width for formatting; with half-width characters counted as 1 space, as per existing implementation.

Implementation aligns with [vscode-markdown](https://github.com/yzhang-gh/vscode-markdown/blob/cfd568bf37223ac60d104f7dc6b2cd79ae130fda/src/tableFormatter.ts#L140) and [Cucumber Autocomplete extension](https://github.com/alexkrechik/VSCucumberAutoComplete/blob/ca571bc1ef434bbd7ba8c66ad76cd384947ba491/gserver/src/format.ts#L36).

### ⚡️ What's your motivation? 

Fixes cucumber/vscode#99.

Present formatted example:

```gherkin
Feature: Full width characters

  Scenario Outline: Format tables with full width characters
    Given a step table with full width characters
      | 路      | bar |
      | 路路路路路路 |  2步 |
      | 路路路    |  2步 |
```

Amended formatted example

> __Note:__ Appearance varies depending on font support with browsers or systems

```gherkin
Feature: Full width characters

  Scenario Outline: Format tables with full width characters
    Given a step table with full width characters
      | 路           | bar |
      | 路路路路路路 | 2步 |
      | 路路路       | 2步 |
```

#### Formatted example using a full-width character supported font

With the aforementioned 'amended formatted example' and the [Iosevka font](https://github.com/be5invis/Iosevka/releases/tag/v28.0.5), it appears as follows in the browser...

Screenshot 2024-01-20 at 16 50 35

...and as follows in VSCode:

Screenshot 2024-01-20 at 16 50 23

### 🏷️ What kind of change is this?

- :bug: Bug fix (non-breaking change which fixes a defect)

### ♻️ Anything particular you want feedback on?

Whether should be classed as a 'bug' or an 'enhancement'.

### 📋 Checklist:

- [x] I agree to respect and uphold the [Cucumber Community Code of Conduct](https://cucumber.io/conduct/)
- [x] I've changed the behaviour of the code
  - [x] I have added/updated tests to cover my changes.
- [x] Users should know about my change
  - [x] I have added an entry to the "Unreleased" section of the [**CHANGELOG**](../blob/main/CHANGELOG.md), linking to this pull request.

### CODE REVIEW

**Review by mpkorstanje — CHANGES_REQUESTED** [review]
[This solution isn't perfect](https://stackoverflow.com/questions/71228251/how-can-i-determine-the-width-of-a-unicode-character). There will be other cases where the table is visually misaligned, probably with flag emojis and such. But as a work around for the what is probably the most common problem I do think this is acceptable. 

That said, as this problem is common to both implementations, please do add an example in the `testdata` folder.

**Comment by mpkorstanje** [comment]
Just noticed the Java implementation doesn't test against the `testdata` set. Still it would be good to add an example there, so if/when we do add tests for that, it will be covered.

**Comment by kieran-ryan** [comment]
My present understanding is that testdata is only used to validate that: parsing - before and after formatting - yields the same messages representation - excluding the formatting itself. To check: modify the formatting of a testdata feature file, and run `npm run test` inside the `javascript` directory; it should pass.

Thus, adding my example to testdata would only really test that CJK characters can be parsed and aren't removed; not the formatting itself - not sure whether that is valuable?

The fix is trivial: adding `assert.strictEqual(gherkinSource, formattedGherkinSource)` - which fails for every feature file as they are unformatted - and of course to reformat the testdata feature files. Though unsure is that best course of action?

Screenshot 2024-02-19 at 22 22 00

Interested to get your perspective on best way forward - and whether should be completed as separate issue:

- [ ] Leave existing testdata untouched to validate messages representation before and after formatting. Consider git submoduling [gherkin](https://github.com/cucumber/gherkin) to reference its testdata without duplicating here - which may have tradeoffs.
- [ ] Reformat the testdata and migrate unit tests into this testdata. Consider `.ndjson` and `.tokens` representations are required or can be removed.
- [ ] Introduce new formatting testdata directory and migrate Java and Javascript test suites to use to eliminate duplication.
- [ ] Something else?

**Comment by mpkorstanje** [comment]
Okay that's more complicated than expected. I was expecting this project to be in a better state then it is.

Let's offload those concerns to https://github.com/cucumber/gherkin-utils/issues/59 and https://github.com/cucumber/gherkin-utils/issues/62.

Feel free to merge and release this.

**Pull request merged**
